### ISSUE TITLE
How to handle change of cart item quantity?

### ISSUE THREAD

**Issue by markphillips100** [mauroservienti/all-our-aggregates-are-wrong-demos#148]
I've noticed the `AddItemToCartHandler` (in sales) adds a new `ShoppingCartItem` for the given request, including the user-selected quantity.  So if a user adds the same product again (new POST request) they would end up with 2 cart items, one each for the same product.

I assume that's why the `GetCart` controller method in sales returns an aggregation of quantity and price grouped around the ProductId?  This also means the user would see a list of individual products with a single quantity and price.  All good and fits the user expectation I imagine.

Removing a product from the cart entirely could be handled by deleting all cart items with a matching product id.  How would you handle a use case where a user wants to change the quantity of an existing product in the cart?

**Comment by mauroservienti** [comment]
> I've noticed the `AddItemToCartHandler` (in sales) adds a new `ShoppingCartItem` for the given request, including the user-selected quantity. So if a user adds the same product again (new POST request) they would end up with 2 cart items, one each for the same product.
> 
> I assume that's why the `GetCart` controller method in sales returns an aggregation of quantity and price grouped around the ProductId? This also means the user would see a list of individual products with a single quantity and price. All good and fits the user expectation I imagine.

That's correct. The feature is designed to allow for compensation. Every request that comes from the UI has a unique request ID that is tracked in the DB along with the request data. Given that the request spans 3 different services one of them might fail or might reject the request and the others should be able to "rollback" or compensate a specific request. If I were to update the shopping cart instead of using an append-only much more data need to be exchanged in case of failure to rollback, making everything much harder or even impossible.

> Removing a product from the cart entirely could be handled by deleting all cart items with matching product id. How would you handle a use case where a user wants to change the quantity of an existing product in the cart?

We can not really send a request that is similar to `change quantity of XYZ to 3`, because we have no idea what to do with the number 3 and it requires the service to calculate the difference with the current quantity. But this doesn't really play nicely with message order if in the meantime another message comes in to add 1. Depending on the order of messages we'll get a different result.

Instead, the UI could send in a request that is something like `change quantity of item XYZ from 4 to 3 (aka -1)`. At this point, each service will insert a new row with a quantity of -1. And regardless of the order of messages, the final quantity will be idempotent.

Delete might be tricky for the same reason if you have concurrency in changing the shopping cart. By removing all the items you might end up removing something that was not meant to be removed:

- 5 items in the cart
- delete
- by the time the delete message is handled:
  - add 1 more item (by a different user)
  - we have now 6 items in the cart
- delete is handled and all 6 items are removed

It might be acceptable or not, it really depends on the business. A solution to that could be:

- 5 items in the cart
- change from 5 to 0 (aka -5)
- by the time the change request (delete) message is handled:
  - add 1 more item (by a different user)
  - we have now 6 items in the cart
- change request (delete) is handled:
  - -5 items are added

The final result is that there is one item in the cart. This is to say that the delete behavior might be different based on the business use case. In this second scenario, the UI or the backend read API in some way need to deal with the fact that there might be cart items with a final quantity of 0, that should not be shown.

**Comment by markphillips100** [comment]
> We can not really send a request that is similar to change quantity of XYZ to 3, because we have no idea what to do with the number 3 and it requires the service to calculate the difference with the current quantity. But this doesn't really play nicely with message order if in the meantime another message comes in to add 1. Depending on the order of messages we'll get a different result.

Azure ServiceBus supports ordering of messages using a Session Id (CartId).  Is this perhaps where infrastructure could help or should we always assume no message order to maximise performance?

> Instead, the UI could send in a request that is something like change quantity of item XYZ from 4 to 3 (aka -1). At this point, each service will insert a new row with a quantity of -1. And regardless of the order of messages, the final quantity will be idempotent.

Sounds good.  And I like how it is independent of message ordering.  This also means we get an audit history of changes to the cart for free.

I really like the way the same method can be applied to a "delete product from cart" to maintain idempotency of the resulting quantity, regardless of message order.

Message order is obviously an important concept to consider or at least having the right processing in place to negate its need.

Just to further explore, suppose Sales and Finance (for payments) both handle AddItemToCart messages. Sales handles PlaceOrder command and emits OrderPlaced. Finance handles OrderPlaced to authorize a charge.

Ignoring for now that the authorization could fail, could Finance authorize a payment for an incorrect amount given it could (theoretically) handle an OrderPlaced event before handling all AddItemToCart messages?

**Comment by mauroservienti** [comment]
> > We can not really send a request that is similar to change quantity of XYZ to 3, because we have no idea what to do with the number 3 and it requires the service to calculate the difference with the current quantity. But this doesn't really play nicely with message order if in the meantime another message comes in to add 1. Depending on the order of messages we'll get a different result.
> 
> Azure ServiceBus supports ordering of messages using a Session Id (CartId). Is this perhaps where infrastructure could help or should we always assume no message order to maximise performance?

Technically speaking yes, the problem with message ordering at the queue level is that it forces to have single process and single-threaded consumers. You cannot scale out in any way. As soon as there two threads (or two processes) dequeuing messages the original order cannot be guaranteed.

This is a good article about the problem of ordered delivery https://particular.net/blog/you-dont-need-ordered-delivery

> > Instead, the UI could send in a request that is something like change quantity of item XYZ from 4 to 3 (aka -1). At this point, each service will insert a new row with a quantity of -1. And regardless of the order of messages, the final quantity will be idempotent.
> 
> Sounds good. And I like how it is independent of message ordering. This also means we get an audit history of changes to the cart for free.

Correct.

> Just to further explore, suppose Sales and Finance (for payments) both handle AddItemToCart messages. Sales handles PlaceOrder command and emits OrderPlaced. Finance handles OrderPlaced to authorize a charge.
> 
> Ignoring for now that the authorization could fail, could Finance authorize a payment for an incorrect amount given it could (theoretically) handle an OrderPlaced event before handling all AddItemToCart messages?

the whole process should be designed to explicitly avoid that. It could be something like:

- add item(s) to cart
- proceed to checkout (freezes the cart)
- a late add to cart comes in (rejected the cart is frozen)
- on the checkout page show the cart content so that users can realize that the last item they were adding is not there and can go back

This kind of approach makes so that what is unlikely to happen cannot happen as the cart is frozen as soon as the check-out process is started.

**Comment by markphillips100** [comment]
> Technically speaking yes, the problem with message ordering at the queue level is that it forces to have single process and single-threaded consumers. You cannot scale out in any way. As soon as there two threads (or two processes) dequeuing messages the original order cannot be guaranteed.

Ah yes, I forget about the fact we'd want multiple consumers.  Makes total sense.  I'll take a look at the blog too.

The process outlined makes sense to me from a single context like Sales, but how does a separate service like Shipping know it should accept or reject an AddItem given each service can receive events in any order?  In other words, what's to stop the following scenario:

- add item(s) to cart
- Shipping service becomes inoperable (due to some transient issue for example)
- proceed to checkout (freezes the cart in Sales) and publishes OrderPlaced
- a late add to cart comes in (rejected by Sales as the cart is frozen)
- Shipping service becomes operable again and processes both AddToCart and OrderPlaced which can be in any order.  How would Shipping know if The AddToCart should be accepted or rejected?  I'm worried quantity would become inconsistent between the services.

**Comment by mauroservienti** [comment]
Services are designed to be autonomous and at the same time cohesive when it comes to business features like the shopping cart in this case. So the shopping cart works if all the services are available. If we assume this is fine it's an operation problem, and we should accept that if there is no shipping there is no shopping cart.

However, the way the sample is designed and I know that being a sample is probably too simplistic, makes so that shipping is not mandatory, sales is the only mandatory one. Both shipping and warehouse serve the shopping cart adding additional information that are not a blocker if they weren't available. If shipping was down we could remove entirely the shipping delivery estimation or the availability in stock that comes from the warehouse service, if the warehouse service was down.

Sales is the only we really need to collect items and start the check out process. Well, we need marketing too to display names and descriptions but those can be cached.
At this point, it meant, in theory, that messages can pile up in the warehouse input queue or in the shipping one. If one of those services really needs to deal with message order they could implement a saga to represent their view of the shopping cart, and use the saga state to handle messages coming out of order e.g. by using the message timestamp to reorder messages once they come in.

Hopefully, this answers your question. Unfortunately, there is no one solution that fits them all when it comes to distributed systems. So the business scenario and its requirements have a drastic impact on service boundaries and on the way each service implements its part of the requirements.

**Comment by markphillips100** [comment]
That all makes perfect sense, and thank you for detailed response.

It's clear to me now that it's very hard (for a startup) to attempt definition of service boundaries when it's not clear what the business requirements are yet.  It would seem those boundaries could change considerably as the (startup) business works out what works best for itself and its customers.

Thanks for your input @mauroservienti, you've been most helpful.

**Comment by mauroservienti** [comment]
> It's clear to me now that it's very hard (for a startup) to attempt definition of service boundaries when it's not clear what the business requirements are yet. It would seem those boundaries could change considerably as the (startup) business works out what works best for itself and its customers.

That's correct. When applying an SOA architecture it's very important that the business is stable and well known; otherwise, boundaries will be blurry and fragile with an important negative impact on the overall architecture.

> Thanks for your input @mauroservienti, you've been most helpful.

Thank you, glad I could help.
